### PR TITLE
Flan RM Update & Enhancement

### PR DESCRIPTION
**Pull request by N0tHorizon**
Flan Readme file updates & enhancements

### CODE REVIEW

**Review by N0tHorizon — COMMENTED** [review]
German Translation Added. Drafted

**Comment by N0tHorizon** [comment]
Dropping German Translation .1+

**Comment by N0tHorizon** [comment]
Ready for review. No more changes necessary, only changes from repo owner.

**Comment by Flemmli97** [comment]
ima be honest... i dont really see much of a point for this PR. like installation and troubleshooting part i dont even think its necessary. also for now the license is arr

**Comment by N0tHorizon** [comment]
Okay. It was just a quick enhancement thing

**Pull request closed without merging**
